tmap = {
    "d": {
        "0": "exp",
        "1": "exp",
        "2": "exp",
        "3": "exp",
        "4": "exp",
        "5": "exp",
        "6": "exp",
        "7": "exp",
        "8": "exp",
        "9": "exp",
    },
    "exp": {" ": "exp "},
    "exp ": {
        "+": "exp op",
        "-": "exp op",
        "*": "exp op",
        "/": "exp op",
        "<": "exp cmp?",
        ">": "exp cmp?",
        "=": "exp cmp",
    },
    "exp cmp?": {"=": "exp cmp", " ": ""},
    "exp cmp": {" ": "exp cmp "},
    "exp cmp ": {
        "0": "bool",
        "1": "bool",
        "2": "bool",
        "3": "bool",
        "4": "bool",
        "5": "bool",
        "6": "bool",
        "7": "bool",
        "8": "bool",
        "9": "bool",
    },
    "exp op": {" ": "exp op "},
    "exp op ": {
        "0": "exp",
        "1": "exp",
        "2": "exp",
        "3": "exp",
        "4": "exp",
        "5": "exp",
        "6": "exp",
        "7": "exp",
        "8": "exp",
        "9": "exp",
    },
    "bool": {" ": "bool "},
    "bool ": {"-": "bool -"},
    "bool -": {">": "bool ->"},
    "bool ->": {" ": "bool -> "},
    "bool -> ": {
        "0": "exp",
        "1": "exp",
        "2": "exp",
        "3": "exp",
        "4": "exp",
        "5": "exp",
        "6": "exp",
        "7": "exp",
        "8": "exp",
        "9": "exp",
    },
}